app:
  jwt:
    # 비밀번호 아무 거나 해도됨 모아 놓은건 유지관리 편하게 하기위해
    secret: DaeguGreenArthAcademyClass502RoomForJaveSPRINGbOOTFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram3
    username: root
    password: green502

mybatis:
  type-aliases-package: com.green.greengream4
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui.path: /swagger.html
server:
  port: 8082
  #주파수 맞추기위해 작업하고있음
fcm:
  certification: serviceAccountKey.json